In [2]:
import pandas as pd

In [5]:
dados = pd.read_csv("dados_climaticos_ficticios.csv")

In [6]:
dados.head()

    Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
0  1950   304.55             0.20            Sim
1  1951   312.17             0.06            Não
2  1952   310.58            -0.05            Não
3  1953   312.82            -0.10            Não
4  1954   315.65            -0.18            Não

In [7]:
dados.tail()

     Ano  CO2_ppm  Temp_Anomalia_C Evento_Extremo
69  2019   414.88             1.09            Não
70  2020   418.19             1.32            Não
71  2021   415.93             0.89            Sim
72  2022   416.42             1.28            Não
73  2023   419.48             1.00            Não

#### Dicionário de dados
- Ano: ano de registro da informação
- CO2_ppm: Concentração de partícula por milhão (ppm) de CO2 na atmosfera
- Temp_Anomalia_C: Diferença de temperatura média no ano com a temperatura média histórica em graus celsius
- Evento_Extremo: Indicação Categórica Sim/Não de ocorrência de evento extremo no ano

In [8]:
dados_p1 = dados[dados["Ano"] < 1975]
dados_p2 = dados[((dados["Ano"] >= 1975) & (dados["Ano"] < 2000))]
dados_p3 = dados[dados["Ano"] >= 2000]

In [9]:
dados_p2.describe()

               Ano     CO2_ppm  Temp_Anomalia_C
count    25.000000   25.000000        25.000000
mean   1987.000000  366.024400         0.573600
std       7.359801   11.487436         0.180182
min    1975.000000  346.630000         0.270000
25%    1981.000000  356.110000         0.440000
50%    1987.000000  367.270000         0.550000
75%    1993.000000  374.970000         0.660000
max    1999.000000  385.860000         1.000000